#!/bin/bash

usage() {
	echo "usage: $0 [build_options]" >&2
}

repo=$(basename $0)
(( $# > 0 )) && build_options=("$@") || build_options=('-f')

[[ ! -r description ]] && echo 'Invalid source image' >&2 && usage && exit 2

imgname=$(sed -rn  's/^[[:space:]]*name[[:space:]]*=[[:space:]]*([^[:space:]]+)[[:space:]]*/\1/p' description)
imgver=$(sed -rn  's/^[[:space:]]*version[[:space:]]*=[[:space:]]*([^[:space:]]+)[[:space:]]*/\1/p' description)

echo "Building image $imgname v$imgver and pushing it on repo $repo"

# build new version
is build "${build_options[@]}" || exit 1

# is v5 doesn't return != 0 if ctrl+c is pressed, we check manually
[[ -f "$imgname-$imgver.isimage" ]] || exit 1

# delete old version
is del -fp "$repo/$imgname:$imgver"

# add new version
is add "$repo" "$imgname-$imgver.isimage"

# vim:set ts=2 sw=2 ft=sh noet:
